version : '3'


services:
  web:
    build:
      context: .
      dockerfile: print_system_docker_file
    container_name: print_system_web
    volumes:
      - ./src:/src
    ports:
      - '8000:8000'
    command: sh -c 'python3 manage.py migrate & python3 manage.py runserver 0.0.0.0:8000'
    env_file:
      - db_keys.txt
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: print_system_db
    env_file:
      - db_keys.txt